### ISSUE TITLE
Error in lpl-thumbnails-downloader

### ISSUE THREAD

**Issue by mspykerez** [Mte90/Script#6]
Hi
I'm getting this error when downloading for this playlist: https://1fichier.com/?80m4v89knx0jwhpsex8o
`Not found World is Populated by Twonks, The (2006)(Cree, Edward)[CSSCGC] at https://raw.githubusercontent.com/libretro-thumbnails/Sinclair_-_ZX_Spectrum/master/Named_Boxarts/World%20is%20Populated%20by%20Twonks%2C%20The%20%282006%29%28Cree%2C%20Edward%29%5BCSSCGC%5D.png
Traceback (most recent call last):
  File "C:\Users\rsmiguel\Desktop\playlist\lpl-thumbnails-downloader.py", line 111, in <module>
    download_image(folder, console, item['label'], False)
  File "C:\Users\rsmiguel\Desktop\playlist\lpl-thumbnails-downloader.py", line 83, in download_image
    try_game_name = s[1] + ', ' + s[0].replace(', ', '')
IndexError: list index out of range`

Can you plx fix it? 
Thanks a lot!

**Comment by Mte90** [comment]
Now should be fixed

**Comment by mspykerez** [comment]
Not really. It now only processes more stuff before the error occurs:

`Not found Worlds of Fantasy, The (2012)(Westwood, Steve) at https://raw.githubusercontent.com/libretro-thumbnails/Sinclair_-_ZX_Spectrum/master/Named_Boxarts/Worlds%20of%20Fantasy%2C%20The%20%282012%29%28Westwood%2C%20Steve%29.png
Traceback (most recent call last):
  File "C:\Users\rsmiguel\Desktop\playlist\lpl-thumbnails-downloader.py", line 111, in <module>
    download_image(folder, console, item['label'], False)
  File "C:\Users\rsmiguel\Desktop\playlist\lpl-thumbnails-downloader.py", line 83, in download_image
    try_game_name = s[1] + ', ' + s[0].replace(', ', '')
IndexError: list index out of range
PS C:\Users\rsmiguel\Desktop\playlist>`

**Comment by Mte90** [comment]
Uhm I released a new version should handle better the errors in that part
